import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import { HotspotCard } from "./HotspotCard";
function Empty({ text }) {
    return (_jsx("div", { className: "rounded-[1.4rem] bg-white/70 p-5 text-sm text-[var(--ink-soft)]", children: text }));
}
export function HotspotPanel({ hotspots, loading, selectedIds, expandedReasons, onSelectAll, onSelectHotspot, onExpandAll, onCollapseAll, onToggleReason, }) {
    if (loading) {
        return _jsx(Empty, { text: "\u52A0\u8F7D\u4E2D..." });
    }
    if (hotspots.length === 0) {
        return _jsx(Empty, { text: "\u8FD8\u6CA1\u6709\u70ED\u70B9\u7C07\u3002\u521B\u5EFA\u4E00\u4E2A\u4E3B\u9898\u70ED\u70B9\u76D1\u63A7\u540E\uFF0C\u518D\u624B\u52A8\u89E6\u53D1\u4E00\u6B21\u626B\u63CF\u3002" });
    }
    const allExpanded = hotspots.every((h) => expandedReasons.has(h.id));
    return (_jsxs(_Fragment, { children: [_jsx("div", { className: "mb-4 overflow-hidden rounded-2xl border border-white/20 bg-white/60 p-4 shadow-[0_4px_24px_rgba(0,0,0,0.06)] backdrop-blur-xl", children: _jsxs("div", { className: "flex flex-wrap items-center gap-3", children: [_jsxs("label", { className: "group flex cursor-pointer items-center gap-3 rounded-xl px-3 py-2 transition-all hover:bg-white/50", children: [_jsxs("div", { className: "relative", children: [_jsx("input", { type: "checkbox", checked: selectedIds.size === hotspots.length && hotspots.length > 0, onChange: (e) => onSelectAll(e.target.checked), className: "peer h-5 w-5 cursor-pointer rounded-md border-2 border-[rgba(8,17,31,0.15)] text-[var(--ember)] transition-all checked:border-[var(--ember)] checked:bg-[var(--ember)] hover:border-[var(--ember)]/50 focus:ring-2 focus:ring-[var(--ember)]/20 focus:ring-offset-2" }), _jsx("svg", { className: "pointer-events-none absolute left-1/2 top-1/2 h-3 w-3 -translate-x-1/2 -translate-y-1/2 text-white opacity-0 peer-checked:opacity-100", fill: "none", stroke: "currentColor", viewBox: "0 0 24 24", children: _jsx("path", { strokeLinecap: "round", strokeLinejoin: "round", strokeWidth: 3, d: "M5 13l4 4L19 7" }) })] }), _jsxs("div", { className: "flex flex-col", children: [_jsx("span", { className: "text-sm font-semibold text-[var(--ink)]", children: "\u5168\u9009" }), _jsx("span", { className: "text-xs text-[var(--ink-soft)]", children: selectedIds.size > 0 ? `已选 ${selectedIds.size} / ${hotspots.length}` : `${hotspots.length} 个热点` })] })] }), _jsx("div", { className: "h-10 w-px bg-gradient-to-b from-transparent via-[rgba(8,17,31,0.08)] to-transparent" }), _jsxs("button", { type: "button", onClick: allExpanded ? onCollapseAll : onExpandAll, className: "group flex items-center gap-2 rounded-xl bg-white px-4 py-2 text-sm font-medium text-[var(--ink-soft)] shadow-sm transition-all duration-200 hover:bg-[var(--ember-soft)] hover:text-[var(--ember)] hover:shadow-[0_4px_12px_rgba(239,68,68,0.15)]", children: [_jsx("svg", { className: `h-4 w-4 transition-transform duration-300 ${allExpanded ? "rotate-180" : ""}`, fill: "none", stroke: "currentColor", viewBox: "0 0 24 24", children: _jsx("path", { strokeLinecap: "round", strokeLinejoin: "round", strokeWidth: 2, d: "M19 9l-7 7-7-7" }) }), allExpanded ? "全部折叠" : "全部展开"] })] }) }), hotspots.map((hotspot) => (_jsx(HotspotCard, { hotspot: hotspot, selected: selectedIds.has(hotspot.id), onSelect: onSelectHotspot, expandedReasons: expandedReasons, onToggleReason: onToggleReason }, hotspot.id)))] }));
}
export default HotspotPanel;
